
export type $Event = Event
& AnimationEvent
& BeforeUnloadEvent
& BlobEvent
& ClipboardEvent
& CloseEvent
& CompositionEvent
& CustomEvent
& DeviceMotionEvent
& DeviceOrientationEvent
& DragEvent
& ErrorEvent
& FocusEvent
& FontFaceSetLoadEvent
& FormDataEvent
& GamepadEvent
& HashChangeEvent
& IDBVersionChangeEvent
& InputEvent
& KeyboardEvent
& MessageEvent
& MouseEvent
& OfflineAudioCompletionEvent
& PageTransitionEvent
& PaymentRequestUpdateEvent
& PointerEvent
& PopStateEvent
& ProgressEvent
& RTCDataChannelEvent
& RTCPeerConnectionIceEvent
& StorageEvent
& SubmitEvent
& TouchEvent
& TrackEvent
& TransitionEvent
& UIEvent
& WebGLContextEvent
& WheelEvent